/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author diyas
 */
public class ReceptionistDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionistDashboard
     */
    public ReceptionistDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Bookingmanagementbutton = new javax.swing.JButton();
        GuestManagementbutton = new javax.swing.JButton();
        billingbutton = new javax.swing.JButton();
        Logoutbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("Receptionist Dashboard");

        Bookingmanagementbutton.setBackground(new java.awt.Color(0, 153, 153));
        Bookingmanagementbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bookingmanagementbutton.setForeground(new java.awt.Color(255, 255, 255));
        Bookingmanagementbutton.setText("Booking Management");
        Bookingmanagementbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingmanagementbuttonActionPerformed(evt);
            }
        });

        GuestManagementbutton.setBackground(new java.awt.Color(102, 102, 0));
        GuestManagementbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GuestManagementbutton.setForeground(new java.awt.Color(255, 255, 255));
        GuestManagementbutton.setText("Guest Management");
        GuestManagementbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestManagementbuttonActionPerformed(evt);
            }
        });

        billingbutton.setBackground(new java.awt.Color(102, 0, 0));
        billingbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        billingbutton.setForeground(new java.awt.Color(255, 255, 255));
        billingbutton.setText("Billing and Payment");
        billingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingbuttonActionPerformed(evt);
            }
        });

        Logoutbutton.setText("Logout");
        Logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logoutbutton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(Bookingmanagementbutton)
                            .addGap(65, 65, 65)
                            .addComponent(GuestManagementbutton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(billingbutton))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bookingmanagementbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuestManagementbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(billingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logoutbutton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingmanagementbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingmanagementbuttonActionPerformed
        // TODO add your handling code here:
        BookingManagement BM = new BookingManagement();
        BM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookingmanagementbuttonActionPerformed

    private void GuestManagementbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestManagementbuttonActionPerformed
        // TODO add your handling code here:
        GuestManagement GM = new GuestManagement();
        GM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GuestManagementbuttonActionPerformed

    private void billingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingbuttonActionPerformed
        // TODO add your handling code here:
        Billing B = new Billing();
        B.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_billingbuttonActionPerformed

    private void LogoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbuttonActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookingmanagementbutton;
    private javax.swing.JButton GuestManagementbutton;
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JButton billingbutton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
